[project]
name = "whatsapp-commerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic",
    "asyncpg",
    "bcrypt>=5.0.0",
    "fastapi",
    "google-genai",
    "httpx",
    "passlib[bcrypt]",
    "pydantic-settings",
    "python-jose[cryptography]",
    "python-multipart",
    "sqlalchemy[asyncio]",
    "sse-starlette",
    "uvicorn[standard]",
]
